n1 = int(input("Digite um número"))
print("A tabuada de {} estará logo abaixo".format(n1))
print("1x5=",end="")
print(n1*1)
print("2x5=",end="")
print(n1*2)
print("3x5=",end="")
print(n1*3)
print("4x5=",end="")
print(n1*4)
print("5x5=",end="")
print(n1*5)
print("6x5=",end="")
print(n1*6)
print("7x5=",end="")
print(n1*7)
print("8x5=",end="")
print(n1*8)
print("9x5=",end="")
print(n1*9)
print("10x5=",end="")
print(n1*10)

#OU

n1 = int(input("Digite um número"))
print("-"*12)
print("{} x {} = {}".format(n1,1,n1*1))
print("{} x {} = {}".format(n1,2,n1*2))
print("{} x {} = {}".format(n1,3,n1*3))
print("{} x {} = {}".format(n1,4,n1*4))
print("{} x {} = {}".format(n1,5,n1*5))
print("{} x {} = {}".format(n1,6,n1*6))
print("{} x {} = {}".format(n1,7,n1*7))
print("{} x {} = {}".format(n1,8,n1*8))
print("{} x {} = {}".format(n1,9,n1*9))
print("{} x {} = {}".format(n1,10,n1*10))
print("-"*12)

#Pode colocar":2" dentro da máscara se quiser deixar mais reto/organizado
#
